
version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myappdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d 
  backend:
    build: ./backend
    container_name: node_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: myappdb
      DB_PORT: 3306
      ACCESS_TOKEN_SECRET: supersecretaccesstoken
      REFRESH_TOKEN_SECRET: supersecretrefreshtoken
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  # frontend:
  #   build: ./frontend
  #   container_name: node_frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   # environment:
  #   #   DB_HOST: mysql
  #   #   DB_USER: appuser
  #   #   DB_PASSWORD: apppass
  #   #   DB_NAME: myappdb
  #   #   DB_PORT: 3306
  #   #   ACCESS_TOKEN_SECRET: supersecretaccesstoken
  #   #   REFRESH_TOKEN_SECRET: supersecretrefreshtoken
  #   volumes:
  #     - ./frontend:/usr/src/app
  #   command: yarn dev


volumes:
  db_data:
